spring.application.name=fs-inventory
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${AUTH_PUBLIC_JWT_URL:http://auth-service:8081/api/internal/auth/.well-known/jwks.json}
server.port=${SERVER_PORT:8084}
#DB
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:none}
#Messaging
app.exchange.order-exchange=${ORDER_EXCHANGE:order-exchange}
app.routing-key.order-paid=${ROUTING_KEY_ORDER_PAID:order.paid}
app.queue.commit-reservation-queue=${COMMIT_RESERVATION_QUEUE:inventory-commit-reservation-queue}



